### ISSUE TITLE
WDI package

### ISSUE THREAD

**Issue by vincentarelbundock** [GIST-ORNL/wbstats#2]
FYI,

https://cran.r-project.org/web/packages/WDI/index.html
https://github.com/vincentarelbundock/WDI

**Comment by jpiburn** [comment]
Vincent,

Thank you for sharing those links. I am certainly aware of your work on the `WDI` package, it most definitely served as the inspiration for this one. In fact, my initial intent was to build out `WDI` and submit it for your review, but for various reasons related to work and scope, I decided to create `wbstats` as an independent package. 

I hope this didn't come across in a negative light, as that of course was not the intent.

**Comment by vincentarelbundock** [comment]
;)
