### ISSUE TITLE
Congo Dem Rep code "CD" not working

### ISSUE THREAD

**Issue by wave-electron** [GIST-ORNL/wbstats#3]
I designed my shiny app to use iso2 codes rather than iso3 codes. 

However, I've noticed Congo Dem. Rep. iso2 code "CD"  can't fetch the data. 

```
data <- wb(country = c("CD") ,indicator = "SP.POP.TOTL", startdate = 1960, enddate = 2015)
Warning message:
  No data was returned for any requested country and indicator. Returning empty data frame
```

using the iso3 code "COD" seems to work.  I was wondering if this is a bug?

Here's a screen shot from the app with Congo Dem. Rep. missing its data. 

![screen shot 2017-05-23 at 3 54 23 pm](https://cloud.githubusercontent.com/assets/16273780/26340156/26ed6dd0-3fd0-11e7-9d1b-e4ebbb84c31a.png)

**Comment by jpiburn** [comment]
@wave-electron Thanks for catching this. It looks to be bug on the World Bank side. Here is the API call that your query above gets

http://api.worldbank.org/countries/CD/indicators/SP.POP.TOTL?date=1960:2015&format=json

Here is the returned json
`[{"page":0,"pages":0,"per_page":null,"total":0},null]`

When I use the iso3 code `COD` in the above url it works as expected., as does using iso2 codes for other countries. I will email the WB this morning about it. I'll report back what they say. Hopefully they reply promptly.

Jesse

**Comment by tgherzog** [comment]
Hi: World Bank guy here. This does indeed appear to be a bug in the API. I've reported it to our development team for them to fix. Typically takes 1-2 days. I'll report back...

**Comment by tgherzog** [comment]
This should be fixed now.

**Comment by jpiburn** [comment]
@tgherzog Thanks for the quick turn around. @wave-electron can you confirm that it is working for you? if so I'll close this issue

**Comment by wave-electron** [comment]
Thanks for the quick response.

**Comment by wave-electron** [comment]
Yep. Working at my end.

**Comment by jpiburn** [comment]
Great. Closing this issue out. If only all software issues were this fast and painless to fix :)
